title: Prashant Chikhalkar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:

<a href="https://www.linkedin.com/in/prashant-chikhalkar-90893338/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
